// -s source directory
// -t target directory
// -p scope
// -h custom home page
// -a custom banner
// -g source code url where code is hosted
java -jar apexdoc.jar

-s "D:\MavensMate\001_Denali_Alpha\src\classes"

-t "D:\MavensMate\001_Denali_Alpha\ApexDoc"

-p "global;public;private;testmethod;webService"

-h "D:\MavensMate\001_Denali_Alpha\ApexDoc\homepage.htm"

-a "D:\MavensMate\001_Denali_Alpha\ApexDoc\projectheader.htm"




java -jar "C:\Program Files\Zulu\zulu-11\lib\apexdoc.jar" -s "D:\Addepar\Addeforce\Setup SFDX Environment\HelloWorldLightningComponent\force-app\main\default\classes" -t "D:\Addepar\Addeforce\Setup SFDX Environment\HelloWorldLightningComponent\ApexDocContent" -p "global;public;private;testmethod;webService" -h "D:\Addepar\Addeforce\Setup SFDX Environment\HelloWorldLightningComponent\ApexDocContent\homepage.htm" -a "D:\Addepar\Addeforce\Setup SFDX Environment\HelloWorldLightningComponent\ApexDocContent\projectheader.htm" 